import "./global.css";

import Navbar from "../components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark flex h-screen w-screen text-whiteColor bg-darkBg">
        <Navbar />
        <main className="w-full">{children}</main>
      </body>
    </html>
  );
}
