import "./global.css";

import Navbar from "./Navbar";

export const revalidate = 0;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="dark flex h-screen w-screen text-whiteColor bg-darkBg">
        {/* @ts-expect-error Async Server Component */}
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
