name: Publish

on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const package = JSON.parse(fs.readFileSync("./package.json"));

            try {
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const newRelease = await github.rest.repos.createRelease({
                owner,
                repo,
                name: package.version,
                tag_name: `v${package.version}`,
                draft: true,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
