name: Publish

on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install
